# Generated by Django 3.2.5 on 2021-07-31 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, 'Не меньше 1 ед')], verbose_name='Количество ингредиентов'),
        ),
    ]
