# Generated by Django 3.2.5 on 2021-07-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredients_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='tags', to='recipes.Tag', verbose_name='Тэг'),
        ),
    ]
