# Generated by Django 3.2.5 on 2021-07-28 14:25

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('guest', 'guest'), ('auth_user', 'auth_user'), ('admin', 'admin')], default='guest', max_length=50, verbose_name='Роль пользователя')),
                ('login', models.CharField(help_text='Имя для авторизации на сайте', max_length=200, unique=True, verbose_name='Логин')),
                ('password', models.CharField(help_text='Пароль для авторизации на сайте', max_length=200, verbose_name='Пароль')),
                ('first_name', models.CharField(help_text='Имя под которым вы будете отображаться на сайте', max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия под которой вы будете отображаться на сайте', max_length=200, verbose_name='Фамилия')),
                ('email', models.EmailField(help_text='Адрес вашей эл.почты', max_length=254, unique=True, verbose_name='Email')),
                ('bio', models.TextField(help_text='Расскажите о себе', null=True, verbose_name='О пользователе')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
